
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizers;

import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.Arrays;
import Classes.Utility.*;
import Classes.Abstract.Expresion;
import Classes.Abstract.Instruccion;
import Classes.Expression.*;
import Classes.Instruction.*;
import Classes.Objects.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Terminal.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\070\000\002\002\004\000\002\002\003\000\002\007" +
    "\004\000\002\007\003\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\005\007\000\002\006\004\000" +
    "\002\010\005\000\002\011\007\000\002\012\010\000\002" +
    "\012\006\000\002\012\004\000\002\015\007\000\002\016" +
    "\005\000\002\017\012\000\002\020\005\000\002\021\007" +
    "\000\002\022\011\000\002\023\005\000\002\024\005\000" +
    "\002\025\005\000\002\026\005\000\002\027\006\000\002" +
    "\030\014\000\002\031\003\000\002\031\003\000\002\031" +
    "\003\000\002\031\003\000\002\031\003\000\002\031\003" +
    "\000\002\031\003\000\002\031\003\000\002\031\003\000" +
    "\002\031\003\000\002\031\003\000\002\031\003\000\002" +
    "\031\003\000\002\032\005\000\002\032\005\000\002\032" +
    "\005\000\002\032\005\000\002\032\005\000\002\033\005" +
    "\000\002\033\005\000\002\033\004\000\002\034\010\000" +
    "\002\034\006\000\002\034\010\000\002\034\010\000\002" +
    "\035\005\000\002\036\005\000\002\036\003\000\002\037" +
    "\003\000\002\037\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\224\000\010\030\005\043\014\054\013\001\002\000" +
    "\012\002\ufffe\030\ufffe\043\ufffe\054\ufffe\001\002\000\004" +
    "\004\201\001\002\000\004\002\200\001\002\000\012\002" +
    "\ufffd\030\ufffd\043\ufffd\054\ufffd\001\002\000\012\002\ufffc" +
    "\030\ufffc\043\ufffc\054\ufffc\001\002\000\012\002\000\030" +
    "\005\043\014\054\013\001\002\000\012\002\ufffb\030\ufffb" +
    "\043\ufffb\054\ufffb\001\002\000\004\020\162\001\002\000" +
    "\004\004\015\001\002\000\004\020\016\001\002\000\004" +
    "\044\017\001\002\000\004\045\153\001\002\000\004\021" +
    "\152\001\002\000\004\046\023\001\002\000\004\047\121" +
    "\001\002\000\004\026\024\001\002\000\042\005\045\006" +
    "\052\017\040\022\042\036\043\037\037\040\035\041\050" +
    "\042\036\060\030\061\027\062\041\063\033\064\034\065" +
    "\046\066\044\001\002\000\034\007\uffe7\011\uffe7\012\uffe7" +
    "\013\uffe7\014\uffe7\015\uffe7\016\uffe7\021\uffe7\023\uffe7\025" +
    "\uffe7\027\uffe7\034\uffe7\047\uffe7\001\002\000\034\007\uffe5" +
    "\011\uffe5\012\uffe5\013\uffe5\014\uffe5\015\uffe5\016\uffe5\021" +
    "\uffe5\023\uffe5\025\uffe5\027\uffe5\034\uffe5\047\uffe5\001\002" +
    "\000\036\007\uffca\011\uffca\012\uffca\013\uffca\014\uffca\015" +
    "\uffca\016\uffca\021\uffca\023\uffca\025\uffca\027\uffca\032\uffca" +
    "\034\uffca\047\uffca\001\002\000\036\007\uffcb\011\uffcb\012" +
    "\uffcb\013\uffcb\014\uffcb\015\uffcb\016\uffcb\021\uffcb\023\uffcb" +
    "\025\uffcb\027\uffcb\032\uffcb\034\uffcb\047\uffcb\001\002\000" +
    "\034\007\uffe6\011\uffe6\012\uffe6\013\uffe6\014\uffe6\015\uffe6" +
    "\016\uffe6\021\uffe6\023\uffe6\025\uffe6\027\uffe6\034\uffe6\047" +
    "\uffe6\001\002\000\034\007\uffe4\011\uffe4\012\uffe4\013\uffe4" +
    "\014\uffe4\015\uffe4\016\uffe4\021\uffe4\023\uffe4\025\uffe4\027" +
    "\uffe4\034\uffe4\047\uffe4\001\002\000\034\007\uffe1\011\uffe1" +
    "\012\uffe1\013\uffe1\014\uffe1\015\uffe1\016\uffe1\021\uffe1\023" +
    "\uffe1\025\uffe1\027\uffe1\034\uffe1\047\uffe1\001\002\000\034" +
    "\007\uffe0\011\uffe0\012\uffe0\013\uffe0\014\uffe0\015\uffe0\016" +
    "\uffe0\021\uffe0\023\uffe0\025\uffe0\027\uffe0\034\uffe0\047\uffe0" +
    "\001\002\000\004\024\114\001\002\000\034\007\uffdf\011" +
    "\uffdf\012\uffdf\013\uffdf\014\uffdf\015\uffdf\016\uffdf\021\uffdf" +
    "\023\uffdf\025\uffdf\027\uffdf\034\uffdf\047\uffdf\001\002\000" +
    "\004\024\111\001\002\000\042\005\045\006\052\017\040" +
    "\022\042\036\043\037\037\040\035\041\050\042\036\060" +
    "\030\061\027\062\041\063\033\064\034\065\046\066\044" +
    "\001\002\000\034\007\uffe2\011\uffe2\012\uffe2\013\uffe2\014" +
    "\uffe2\015\uffe2\016\uffe2\021\uffe2\023\uffe2\025\uffe2\027\uffe2" +
    "\034\uffe2\047\uffe2\001\002\000\042\005\045\006\052\017" +
    "\040\022\042\036\043\037\037\040\035\041\050\042\036" +
    "\060\030\061\027\062\041\063\033\064\034\065\046\066" +
    "\044\001\002\000\004\024\076\001\002\000\034\007\uffdd" +
    "\011\uffdd\012\uffdd\013\uffdd\014\uffdd\015\uffdd\016\uffdd\021" +
    "\uffdd\023\uffdd\025\uffdd\027\uffdd\034\uffdd\047\uffdd\001\002" +
    "\000\034\007\uffdc\011\uffdc\012\uffdc\013\uffdc\014\uffdc\015" +
    "\uffdc\016\uffdc\021\uffdc\023\uffdc\025\uffdc\027\uffdc\034\uffdc" +
    "\047\uffdc\001\002\000\034\007\uffde\011\uffde\012\uffde\013" +
    "\uffde\014\uffde\015\uffde\016\uffde\021\uffde\023\uffde\025\uffde" +
    "\027\uffde\034\uffde\047\uffde\001\002\000\034\007\uffe3\011" +
    "\uffe3\012\uffe3\013\uffe3\014\uffe3\015\uffe3\016\uffe3\021\uffe3" +
    "\023\uffe3\025\uffe3\027\uffe3\034\uffe3\047\uffe3\001\002\000" +
    "\004\024\071\001\002\000\022\007\054\011\061\012\060" +
    "\013\056\014\055\015\057\016\053\047\ufff0\001\002\000" +
    "\034\007\uffdb\011\uffdb\012\uffdb\013\uffdb\014\uffdb\015\uffdb" +
    "\016\uffdb\021\uffdb\023\uffdb\025\uffdb\027\uffdb\034\uffdb\047" +
    "\uffdb\001\002\000\042\005\045\006\052\017\040\022\042" +
    "\036\043\037\037\040\035\041\050\042\036\060\030\061" +
    "\027\062\041\063\033\064\034\065\046\066\044\001\002" +
    "\000\042\005\045\006\052\017\040\022\042\036\043\037" +
    "\037\040\035\041\050\042\036\060\030\061\027\062\041" +
    "\063\033\064\034\065\046\066\044\001\002\000\042\005" +
    "\045\006\052\017\040\022\042\036\043\037\037\040\035" +
    "\041\050\042\036\060\030\061\027\062\041\063\033\064" +
    "\034\065\046\066\044\001\002\000\042\005\045\006\052" +
    "\017\040\022\042\036\043\037\037\040\035\041\050\042" +
    "\036\060\030\061\027\062\041\063\033\064\034\065\046" +
    "\066\044\001\002\000\042\005\045\006\052\017\040\022" +
    "\042\036\043\037\037\040\035\041\050\042\036\060\030" +
    "\061\027\062\041\063\033\064\034\065\046\066\044\001" +
    "\002\000\042\005\045\006\052\017\040\022\042\036\043" +
    "\037\037\040\035\041\050\042\036\060\030\061\027\062" +
    "\041\063\033\064\034\065\046\066\044\001\002\000\042" +
    "\005\045\006\052\017\040\022\042\036\043\037\037\040" +
    "\035\041\050\042\036\060\030\061\027\062\041\063\033" +
    "\064\034\065\046\066\044\001\002\000\034\007\uffd7\011" +
    "\uffd7\012\060\013\056\014\055\015\057\016\053\021\uffd7" +
    "\023\uffd7\025\uffd7\027\uffd7\034\uffd7\047\uffd7\001\002\000" +
    "\034\007\uffd6\011\uffd6\012\uffd6\013\056\014\055\015\057" +
    "\016\053\021\uffd6\023\uffd6\025\uffd6\027\uffd6\034\uffd6\047" +
    "\uffd6\001\002\000\034\007\uffd4\011\uffd4\012\uffd4\013\uffd4" +
    "\014\uffd4\015\uffd4\016\uffd4\021\uffd4\023\uffd4\025\uffd4\027" +
    "\uffd4\034\uffd4\047\uffd4\001\002\000\034\007\uffd8\011\uffd8" +
    "\012\uffd8\013\uffd8\014\uffd8\015\057\016\053\021\uffd8\023" +
    "\uffd8\025\uffd8\027\uffd8\034\uffd8\047\uffd8\001\002\000\034" +
    "\007\uffd9\011\uffd9\012\uffd9\013\056\014\uffd9\015\057\016" +
    "\053\021\uffd9\023\uffd9\025\uffd9\027\uffd9\034\uffd9\047\uffd9" +
    "\001\002\000\034\007\uffda\011\061\012\060\013\056\014" +
    "\055\015\057\016\053\021\uffda\023\uffda\025\uffda\027\uffda" +
    "\034\uffda\047\uffda\001\002\000\034\007\uffd5\011\uffd5\012" +
    "\uffd5\013\uffd5\014\uffd5\015\057\016\uffd5\021\uffd5\023\uffd5" +
    "\025\uffd5\027\uffd5\034\uffd5\047\uffd5\001\002\000\042\005" +
    "\045\006\052\017\040\022\042\036\043\037\037\040\035" +
    "\041\050\042\036\060\030\061\027\062\041\063\033\064" +
    "\034\065\046\066\044\001\002\000\022\007\054\011\061" +
    "\012\060\013\056\014\055\015\057\016\053\027\073\001" +
    "\002\000\042\005\045\006\052\017\040\022\042\036\043" +
    "\037\037\040\035\041\050\042\036\060\030\061\027\062" +
    "\041\063\033\064\034\065\046\066\044\001\002\000\022" +
    "\007\054\011\061\012\060\013\056\014\055\015\057\016" +
    "\053\025\075\001\002\000\034\007\uffcf\011\uffcf\012\uffcf" +
    "\013\uffcf\014\uffcf\015\uffcf\016\uffcf\021\uffcf\023\uffcf\025" +
    "\uffcf\027\uffcf\034\uffcf\047\uffcf\001\002\000\042\005\045" +
    "\006\052\017\040\022\042\036\043\037\037\040\035\041" +
    "\050\042\036\060\030\061\027\062\041\063\033\064\034" +
    "\065\046\066\044\001\002\000\022\007\054\011\061\012" +
    "\060\013\056\014\055\015\057\016\053\027\100\001\002" +
    "\000\042\005\045\006\052\017\040\022\042\036\043\037" +
    "\037\040\035\041\050\042\036\060\030\061\027\062\041" +
    "\063\033\064\034\065\046\066\044\001\002\000\022\007" +
    "\054\011\061\012\060\013\056\014\055\015\057\016\053" +
    "\025\102\001\002\000\034\007\uffd2\011\uffd2\012\uffd2\013" +
    "\uffd2\014\uffd2\015\uffd2\016\uffd2\021\uffd2\023\uffd2\025\uffd2" +
    "\027\uffd2\034\uffd2\047\uffd2\001\002\000\006\023\106\027" +
    "\105\001\002\000\024\007\054\011\061\012\060\013\056" +
    "\014\055\015\057\016\053\023\uffcc\027\uffcc\001\002\000" +
    "\042\005\045\006\052\017\040\022\042\036\043\037\037" +
    "\040\035\041\050\042\036\060\030\061\027\062\041\063" +
    "\033\064\034\065\046\066\044\001\002\000\034\007\uffce" +
    "\011\uffce\012\uffce\013\uffce\014\uffce\015\uffce\016\uffce\021" +
    "\uffce\023\uffce\025\uffce\027\uffce\034\uffce\047\uffce\001\002" +
    "\000\024\007\054\011\061\012\060\013\056\014\055\015" +
    "\057\016\053\023\uffcd\027\uffcd\001\002\000\034\007\uffd3" +
    "\011\uffd3\012\uffd3\013\uffd3\014\uffd3\015\uffd3\016\uffd3\021" +
    "\uffd3\023\uffd3\025\uffd3\027\uffd3\034\uffd3\047\uffd3\001\002" +
    "\000\042\005\045\006\052\017\040\022\042\036\043\037" +
    "\037\040\035\041\050\042\036\060\030\061\027\062\041" +
    "\063\033\064\034\065\046\066\044\001\002\000\022\007" +
    "\054\011\061\012\060\013\056\014\055\015\057\016\053" +
    "\025\113\001\002\000\034\007\uffd1\011\uffd1\012\uffd1\013" +
    "\uffd1\014\uffd1\015\uffd1\016\uffd1\021\uffd1\023\uffd1\025\uffd1" +
    "\027\uffd1\034\uffd1\047\uffd1\001\002\000\042\005\045\006" +
    "\052\017\040\022\042\036\043\037\037\040\035\041\050" +
    "\042\036\060\030\061\027\062\041\063\033\064\034\065" +
    "\046\066\044\001\002\000\022\007\054\011\061\012\060" +
    "\013\056\014\055\015\057\016\053\027\116\001\002\000" +
    "\042\005\045\006\052\017\040\022\042\036\043\037\037" +
    "\040\035\041\050\042\036\060\030\061\027\062\041\063" +
    "\033\064\034\065\046\066\044\001\002\000\022\007\054" +
    "\011\061\012\060\013\056\014\055\015\057\016\053\025" +
    "\120\001\002\000\034\007\uffd0\011\uffd0\012\uffd0\013\uffd0" +
    "\014\uffd0\015\uffd0\016\uffd0\021\uffd0\023\uffd0\025\uffd0\027" +
    "\uffd0\034\uffd0\047\uffd0\001\002\000\004\026\123\001\002" +
    "\000\004\021\ufff2\001\002\000\004\020\124\001\002\000" +
    "\004\050\127\001\002\000\004\021\151\001\002\000\004" +
    "\027\132\001\002\000\004\026\130\001\002\000\042\005" +
    "\045\006\052\017\040\022\042\036\043\037\037\040\035" +
    "\041\050\042\036\060\030\061\027\062\041\063\033\064" +
    "\034\065\046\066\044\001\002\000\022\007\054\011\061" +
    "\012\060\013\056\014\055\015\057\016\053\027\uffed\001" +
    "\002\000\004\051\134\001\002\000\004\027\137\001\002" +
    "\000\004\026\135\001\002\000\042\005\045\006\052\017" +
    "\040\022\042\036\043\037\037\040\035\041\050\042\036" +
    "\060\030\061\027\062\041\063\033\064\034\065\046\066" +
    "\044\001\002\000\022\007\054\011\061\012\060\013\056" +
    "\014\055\015\057\016\053\027\uffec\001\002\000\004\052" +
    "\141\001\002\000\004\027\144\001\002\000\004\026\142" +
    "\001\002\000\042\005\045\006\052\017\040\022\042\036" +
    "\043\037\037\040\035\041\050\042\036\060\030\061\027" +
    "\062\041\063\033\064\034\065\046\066\044\001\002\000" +
    "\022\007\054\011\061\012\060\013\056\014\055\015\057" +
    "\016\053\027\uffeb\001\002\000\004\053\145\001\002\000" +
    "\004\026\147\001\002\000\004\021\uffee\001\002\000\042" +
    "\005\045\006\052\017\040\022\042\036\043\037\037\040" +
    "\035\041\050\042\036\060\030\061\027\062\041\063\033" +
    "\064\034\065\046\066\044\001\002\000\022\007\054\011" +
    "\061\012\060\013\056\014\055\015\057\016\053\021\uffea" +
    "\001\002\000\004\021\uffef\001\002\000\012\002\ufff3\030" +
    "\ufff3\043\ufff3\054\ufff3\001\002\000\004\026\154\001\002" +
    "\000\004\022\155\001\002\000\004\004\156\001\002\000" +
    "\004\027\157\001\002\000\004\004\160\001\002\000\004" +
    "\023\161\001\002\000\004\046\ufff1\001\002\000\004\055" +
    "\164\001\002\000\004\021\176\001\002\000\004\022\165" +
    "\001\002\000\004\004\166\001\002\000\004\023\167\001" +
    "\002\000\004\056\170\001\002\000\004\020\171\001\002" +
    "\000\004\057\172\001\002\000\004\026\173\001\002\000" +
    "\042\005\045\006\052\017\040\022\042\036\043\037\037" +
    "\040\035\041\050\042\036\060\030\061\027\062\041\063" +
    "\033\064\034\065\046\066\044\001\002\000\022\007\054" +
    "\011\061\012\060\013\056\014\055\015\057\016\053\021" +
    "\175\001\002\000\004\021\uffe8\001\002\000\012\002\uffe9" +
    "\030\uffe9\043\uffe9\054\uffe9\001\002\000\012\002\uffff\030" +
    "\uffff\043\uffff\054\uffff\001\002\000\004\002\001\001\002" +
    "\000\004\020\202\001\002\000\004\031\205\001\002\000" +
    "\004\032\212\001\002\000\004\021\210\001\002\000\004" +
    "\026\206\001\002\000\006\060\030\061\027\001\002\000" +
    "\004\032\ufff8\001\002\000\012\002\ufffa\030\ufffa\043\ufffa" +
    "\054\ufffa\001\002\000\004\021\ufff9\001\002\000\004\026" +
    "\213\001\002\000\004\022\214\001\002\000\006\033\216" +
    "\035\217\001\002\000\004\023\226\001\002\000\042\005" +
    "\045\006\052\017\040\022\042\036\043\037\037\040\035" +
    "\041\050\042\036\060\030\061\027\062\041\063\033\064" +
    "\034\065\046\066\044\001\002\000\042\005\045\006\052" +
    "\017\040\022\042\036\043\037\037\040\035\041\050\042" +
    "\036\060\030\061\027\062\041\063\033\064\034\065\046" +
    "\066\044\001\002\000\022\007\054\011\061\012\060\013" +
    "\056\014\055\015\057\016\053\023\ufff4\001\002\000\022" +
    "\007\054\011\061\012\060\013\056\014\055\015\057\016" +
    "\053\034\222\001\002\000\042\005\045\006\052\017\040" +
    "\022\042\036\043\037\037\040\035\041\050\042\036\060" +
    "\030\061\027\062\041\063\033\064\034\065\046\066\044" +
    "\001\002\000\024\007\054\011\061\012\060\013\056\014" +
    "\055\015\057\016\053\023\ufff5\027\224\001\002\000\006" +
    "\033\216\035\217\001\002\000\004\023\ufff6\001\002\000" +
    "\004\021\ufff7\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\224\000\016\002\005\003\003\005\006\007\010\015" +
    "\007\027\011\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\003\176\005\006\015\007\027\011\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\016\017\017\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\020\021\001\001\000\004\021" +
    "\121\001\001\000\002\001\001\000\016\031\050\032\024" +
    "\033\030\034\031\035\046\037\025\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\031\107\032\024\033\030\034\031\035" +
    "\046\037\025\001\001\000\002\001\001\000\020\031\103" +
    "\032\024\033\030\034\031\035\046\036\102\037\025\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\031\067\032\024" +
    "\033\030\034\031\035\046\037\025\001\001\000\016\031" +
    "\066\032\024\033\030\034\031\035\046\037\025\001\001" +
    "\000\016\031\065\032\024\033\030\034\031\035\046\037" +
    "\025\001\001\000\016\031\064\032\024\033\030\034\031" +
    "\035\046\037\025\001\001\000\016\031\063\032\024\033" +
    "\030\034\031\035\046\037\025\001\001\000\016\031\062" +
    "\032\024\033\030\034\031\035\046\037\025\001\001\000" +
    "\016\031\061\032\024\033\030\034\031\035\046\037\025" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\031\071\032\024\033\030\034" +
    "\031\035\046\037\025\001\001\000\002\001\001\000\016" +
    "\031\073\032\024\033\030\034\031\035\046\037\025\001" +
    "\001\000\002\001\001\000\002\001\001\000\016\031\076" +
    "\032\024\033\030\034\031\035\046\037\025\001\001\000" +
    "\002\001\001\000\016\031\100\032\024\033\030\034\031" +
    "\035\046\037\025\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\016\031\106" +
    "\032\024\033\030\034\031\035\046\037\025\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\016" +
    "\031\111\032\024\033\030\034\031\035\046\037\025\001" +
    "\001\000\002\001\001\000\002\001\001\000\016\031\114" +
    "\032\024\033\030\034\031\035\046\037\025\001\001\000" +
    "\002\001\001\000\016\031\116\032\024\033\030\034\031" +
    "\035\046\037\025\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\022\124\023\125\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\031\130\032\024" +
    "\033\030\034\031\035\046\037\025\001\001\000\002\001" +
    "\001\000\004\024\132\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\031\135\032\024\033\030\034\031\035" +
    "\046\037\025\001\001\000\002\001\001\000\004\025\137" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\031" +
    "\142\032\024\033\030\034\031\035\046\037\025\001\001" +
    "\000\002\001\001\000\004\026\145\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\031\147\032\024\033\030" +
    "\034\031\035\046\037\025\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\030\162" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\031\173\032" +
    "\024\033\030\034\031\035\046\037\025\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\006\203" +
    "\010\202\001\001\000\004\011\210\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\037\206\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\012\214\001\001\000\002" +
    "\001\001\000\016\031\220\032\024\033\030\034\031\035" +
    "\046\037\025\001\001\000\016\031\217\032\024\033\030" +
    "\034\031\035\046\037\025\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\031\222\032\024\033\030\034\031" +
    "\035\046\037\025\001\001\000\002\001\001\000\004\012" +
    "\224\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Código Java
    public ArrayList<Instruccion> sentencias;


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= INSTRUCCIONES 
            {
              Object RESULT =null;
		int instleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int instright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Instruccion> inst = (ArrayList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 sentencias = inst; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INSTRUCCIONES ::= INSTRUCCIONES INSTRUCCION 
            {
              ArrayList<Instruccion> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Instruccion> l = (ArrayList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; RESULT.add(i); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INSTRUCCIONES ::= INSTRUCCION 
            {
              ArrayList<Instruccion> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ArrayList<>(Arrays.asList(i));  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCCION ::= ESTRATEGIA 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		CrearEstrategia e = (CrearEstrategia)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INSTRUCCION ::= PARTIDA 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion e = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INSTRUCCION ::= PUNTO_ACCESO 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion e = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ESTRATEGIA ::= PR_strategy TK_id TK_llaveA INSTRUCCIONES_ESTRATEGIA TK_llaveC 
            {
              CrearEstrategia RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int instleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int instright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		InstruccionEstrategia inst = (InstruccionEstrategia)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new CrearEstrategia(n, inst); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ESTRATEGIA",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // INSTRUCCIONES_ESTRATEGIA ::= DECISION_INICIAL REGLAS 
            {
              InstruccionEstrategia RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion i = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Regla> r = (ArrayList<Regla>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new InstruccionEstrategia(i, r); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES_ESTRATEGIA",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // DECISION_INICIAL ::= PR_initial TK_dosPuntos DECISION 
            {
              Expresion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DECISION_INICIAL",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // REGLAS ::= PR_rules TK_dosPuntos TK_corcheteA LISTA_REGLAS TK_corcheteC 
            {
              ArrayList<Regla> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<Regla> l = (ArrayList<Regla>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = l; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("REGLAS",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // LISTA_REGLAS ::= PR_if EXPRESION PR_then EXPRESION TK_coma LISTA_REGLAS 
            {
              ArrayList<Regla> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList<Regla> l = (ArrayList<Regla>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = l; RESULT.add(new Regla(c, a) ); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("LISTA_REGLAS",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // LISTA_REGLAS ::= PR_if EXPRESION PR_then EXPRESION 
            {
              ArrayList<Regla> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ArrayList<Regla>(Arrays.asList(new Regla(c, a))); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("LISTA_REGLAS",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // LISTA_REGLAS ::= PR_else EXPRESION 
            {
              ArrayList<Regla> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion a = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new ArrayList<Regla>(Arrays.asList(new Regla(null, a))); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("LISTA_REGLAS",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // PARTIDA ::= PR_match TK_id TK_llaveA INSTRUCIONES_PARTIDA TK_llaveC 
            {
              Instruccion RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int instleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int instright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		InstruccionesPartida inst = (InstruccionesPartida)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new CrearPartida(n, inst); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("PARTIDA",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // INSTRUCIONES_PARTIDA ::= JUGADORES RONDAS PUNTUACIONES 
            {
              InstruccionesPartida RESULT =null;
		int jleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int jright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Jugadores j = (Jugadores)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Expresion r = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Puntos p = (Puntos)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new InstruccionesPartida(j, r, p); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INSTRUCIONES_PARTIDA",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // JUGADORES ::= PR_players PR_strategies TK_dosPuntos TK_corcheteA TK_id TK_coma TK_id TK_corcheteC 
            {
              Jugadores RESULT =null;
		int j1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int j1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String j1 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int j2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int j2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String j2 = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Jugadores(j1, j2); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("JUGADORES",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // RONDAS ::= PR_rounds TK_dosPuntos EXPRESION 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RONDAS",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // PUNTUACIONES ::= PR_scoring TK_dosPuntos TK_llaveA PUNTOS TK_llaveC 
            {
              Puntos RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Puntos p = (Puntos)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = p; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("PUNTUACIONES",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // PUNTOS ::= COOPERACION_MUTUA TK_coma DEFECCION_MUTUA TK_coma TRAIDOR TK_coma TRAICIONADO 
            {
              Puntos RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		Expresion c = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int trleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int trright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Expresion tr = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int taleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int taright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion ta = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Puntos(c, d, tr, ta); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("PUNTOS",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // COOPERACION_MUTUA ::= PR_cooperacionM TK_dosPuntos EXPRESION 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =  exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("COOPERACION_MUTUA",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // DEFECCION_MUTUA ::= PR_defeccionnM TK_dosPuntos EXPRESION 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =  exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DEFECCION_MUTUA",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // TRAIDOR ::= PR_traidor TK_dosPuntos EXPRESION 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =  exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TRAIDOR",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // TRAICIONADO ::= PR_traicionado TK_dosPuntos EXPRESION 
            {
              Expresion RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT =  exp; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TRAICIONADO",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // PUNTO_ACCESO ::= PR_main TK_llaveA INSTRUCCIONES_ACCESO TK_llaveC 
            {
              Instruccion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new PuntoAcceso(p); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("PUNTO_ACCESO",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // INSTRUCCIONES_ACCESO ::= PR_run TK_corcheteA TK_id TK_corcheteC PR_with TK_llaveA PR_seed TK_dosPuntos EXPRESION TK_llaveC 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		 RESULT = id; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES_ACCESO",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // EXPRESION ::= RELACIONALES 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // EXPRESION ::= LOGICAS 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // EXPRESION ::= DECISION 
            {
              Expresion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Expresion d = (Expresion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // EXPRESION ::= FUNCIONES 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // EXPRESION ::= LISTA 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // EXPRESION ::= PR_random 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // EXPRESION ::= PR_opponent_history 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // EXPRESION ::= PR_self_history 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // EXPRESION ::= PR_round_number 
            {
              Expresion RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // EXPRESION ::= PR_true 
            {
              Expresion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitivo(p, Tipo.BOOLEAN); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // EXPRESION ::= PR_false 
            {
              Expresion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitivo(p, Tipo.BOOLEAN); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // EXPRESION ::= TK_enteros 
            {
              Expresion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitivo(p, Tipo.ENTERO); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // EXPRESION ::= TK_decimales 
            {
              Expresion RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitivo(p, Tipo.DECIMAL); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPRESION",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // RELACIONALES ::= EXPRESION TK_igual EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RELACIONALES",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // RELACIONALES ::= EXPRESION TK_mayorIgual EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RELACIONALES",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // RELACIONALES ::= EXPRESION TK_menorIgual EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RELACIONALES",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // RELACIONALES ::= EXPRESION TK_mayor EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RELACIONALES",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // RELACIONALES ::= EXPRESION TK_menor EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RELACIONALES",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // LOGICAS ::= EXPRESION TK_and EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("LOGICAS",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // LOGICAS ::= EXPRESION TK_or EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("LOGICAS",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // LOGICAS ::= TK_not EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("LOGICAS",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // FUNCIONES ::= PR_get_move TK_parA EXPRESION TK_coma EXPRESION TK_parC 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("FUNCIONES",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // FUNCIONES ::= PR_last_move TK_parA EXPRESION TK_parC 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("FUNCIONES",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // FUNCIONES ::= PR_get_moves_count TK_parA EXPRESION TK_coma EXPRESION TK_parC 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("FUNCIONES",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // FUNCIONES ::= PR_get_last_n_moves TK_parA EXPRESION TK_coma EXPRESION TK_parC 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("FUNCIONES",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // LISTA ::= TK_corcheteA ELEMENTOS TK_corcheteC 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("LISTA",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // ELEMENTOS ::= ELEMENTOS TK_coma EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ELEMENTOS",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // ELEMENTOS ::= EXPRESION 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ELEMENTOS",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // DECISION ::= PR_C 
            {
              Expresion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitivo(d, Tipo.DECISION); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DECISION",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // DECISION ::= PR_D 
            {
              Expresion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Primitivo(d, Tipo.DECISION); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("DECISION",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
