// === 1. Package e imports
package Analizers;
import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.Arrays;

import Classes.Utility.*;
import Classes.Abstract.Expresion;
import Clasess.Abstract.Instruccion;
import Clasess.Expression.*;
import Clasess.Instruction.*;
import Clasess.Objects.*;

// === 2. configuración
parser code
{:
    // Código Java
    public ArrayList<Instruccion> sentencias;
:}

// === 3. terminales

terminal String TK_id, TK_enteros, TK_decimales, TK_igual, TK_diferente, TK_mayor, TK_menor, TK_menorIgual, TK_mayorIgual, TK_or, TK_and, TK_not;
terminal String TK_llaveA, TK_llaveC, TK_corcheteA, TK_corcheteC, TK_parA, TK_parC, TK_dosPuntos, TK_coma;
terminal String PR_strategy, PR_initial, PR_rules, PR_if, PR_then, PR_else, PR_get_move, PR_last_move, PR_get_moves_count, PR_get_last_n_moves, PR_round_number, PR_match, PR_players, PR_strategies, PR_rounds, PR_scoring, PR_cooperacionM, PR_defeccionnM, PR_traidor, PR_traicionado, PR_main, PR_run, PR_with, PR_seed;
terminal PR_C, PR_D;
terminal PR_random, PR_opponent_history, PR_self_history, PR_true, PR_false;

// === 4. no terminales
non terminal INICIO;
non terminal Instruccion INSTRUCCION;
non terminal ESTRATEGIAS;
non terminal CrearEstrategia ESTRATEGIA;
non terminal InstruccionEstrategia INSTRUCCIONES_ESTRATEGIA;
non terminal ArrayList<Instruccion> INSTRUCCIONES;
non terminal Expresion DECISION_INICIAL;
non terminal ArrayList<Regla> REGLAS;
non terminal ArrayList<Regla> LISTA_REGLAS;
non terminal REGLA;
non terminal PARTIDAS;
non terminal Instruccion PARTIDA;
non terminal InstruccionesPartida INSTRUCIONES_PARTIDA;
non terminal Jugadores JUGADORES;
non terminal Expresion RONDAS;
non terminal Puntos PUNTUACIONES;
non terminal Puntos PUNTOS;
non terminal Expresion COOPERACION_MUTUA;
non terminal Expresion DEFECCION_MUTUA;
non terminal Expresion TRAIDOR;
non terminal Expresion TRAICIONADO;
non terminal Instruccion PUNTO_ACCESO;
non terminal INSTRUCCIONES_ACCESO;
non terminal Expresion EXPRESION;
non terminal RELACIONALES;
non terminal LOGICAS;
non terminal FUNCIONES;
non terminal LISTA;
non terminal ELEMENTOS;
non terminal Expresion DECISION;

/*5. Precedencia de Operadores*/
precedence left TK_igual;
precedence left TK_mayor;
precedence left TK_menor;
precedence left TK_mayorIgual;
precedence left TK_menorIgual;
precedence left TK_and;
precedence left TK_or;
precedence right TK_not;

/*6. Gramática*/
start with INICIO;

INICIO ::=  INSTRUCCIONES :inst {: sentencias = inst; :} ;

INSTRUCCIONES ::=
            INSTRUCCIONES :l INSTRUCCION :i {: RESULT = l; RESULT.add(i); :} |
            INSTRUCCION :i               {: RESULT = new ArrayList<>(Arrays.asList(i));  :} ;

INSTRUCCION ::=
            ESTRATEGIA :e {: RESULT = e; :} |
            PARTIDA    :e {: RESULT = e; :} |
            PUNTO_ACCESO :e {: RESULT = e; :};

ESTRATEGIA ::= PR_strategy TK_id :n TK_llaveA INSTRUCCIONES_ESTRATEGIA :inst TK_llaveC {: RESULT = new CrearEstrategia(n, inst); :} ;

INSTRUCCIONES_ESTRATEGIA ::= DECISION_INICIAL :i REGLAS :r {: RESULT = new InstruccionEstrategia(i, r); :} ;

DECISION_INICIAL ::= PR_initial TK_dosPuntos DECISION :d {: RESULT = d; :} ;

REGLAS ::= PR_rules TK_dosPuntos TK_corcheteA LISTA_REGLAS :l TK_corcheteC {: RESULT = l; :} ;

LISTA_REGLAS ::=
            PR_if EXPRESION :c PR_then EXPRESION :a TK_coma LISTA_REGLAS :l  {: RESULT = l; RESULT.add(new Regla(c, a) ); :} |
            PR_if EXPRESION :c PR_then EXPRESION :a                          {: RESULT = new ArrayList<Regla>(Arrays.asList(new Regla(c, a))); :} |
            PR_else EXPRESION :a                                             {: RESULT = new ArrayList<Regla>(Arrays.asList(new Regla(null, a))); :} ;

// === DELCARACION DE PARTIDAS ===

PARTIDA ::= PR_match TK_id :n TK_llaveA INSTRUCIONES_PARTIDA :inst TK_llaveC {: RESULT = new CrearPartida(n, inst); :} ;

INSTRUCIONES_PARTIDA ::= JUGADORES :j RONDAS :r PUNTUACIONES :p {: RESULT = new InstruccionesPartida(j, r, p); :};

JUGADORES ::= PR_players PR_strategies TK_dosPuntos TK_corcheteA TK_id :j1 TK_coma TK_id :j2 TK_corcheteC {: RESULT = new Jugadores(j1, j2); :} ;

RONDAS ::= PR_rounds TK_dosPuntos EXPRESION :exp {: RESULT = exp; :} ;

PUNTUACIONES ::= PR_scoring TK_dosPuntos TK_llaveA PUNTOS :p TK_llaveC {: RESULT = p; :} ;

PUNTOS ::= COOPERACION_MUTUA :c TK_coma DEFECCION_MUTUA :d TK_coma TRAIDOR :tr TK_coma TRAICIONADO :ta {: RESULT = new Puntos(c, d, tr, ta); :} ;

COOPERACION_MUTUA ::= PR_cooperacionM TK_dosPuntos EXPRESION :exp {: RESULT =  exp; :} ;

DEFECCION_MUTUA ::= PR_defeccionnM TK_dosPuntos EXPRESION :exp {: RESULT =  exp; :} ;

TRAIDOR ::= PR_traidor TK_dosPuntos EXPRESION :exp {: RESULT =  exp; :} ;

TRAICIONADO ::= PR_traicionado TK_dosPuntos EXPRESION :exp {: RESULT =  exp; :} ;

// === PUNTO DE ACCESO ===

PUNTO_ACCESO ::= PR_main TK_llaveA INSTRUCCIONES_ACCESO :p TK_llaveC {: RESULT = new PuntoAcceso(p); :} ;

INSTRUCCIONES_ACCESO ::= PR_run TK_corcheteA TK_id :id TK_corcheteC PR_with TK_llaveA PR_seed TK_dosPuntos EXPRESION TK_llaveC {: RESULT = id; :} ;

EXPRESION ::=
            RELACIONALES |
            LOGICAS      |
            DECISION     :d {: RESULT = d; :}|
            FUNCIONES    |
            LISTA       |
            PR_random   |
            PR_opponent_history |
            PR_self_history |
            PR_round_number |
            PR_true      :p {: RESULT = new Primitivo(p, Tipo.BOOLEAN); :} |
            PR_false     :p {: RESULT = new Primitivo(p, Tipo.BOOLEAN); :} |
            TK_enteros   :p {: RESULT = new Primitivo(p, Tipo.ENTERO); :} |
            TK_decimales :p {: RESULT = new Primitivo(p, Tipo.DECIMAL); :} ;

RELACIONALES ::=
            EXPRESION TK_igual EXPRESION |
            EXPRESION TK_mayorIgual EXPRESION |
            EXPRESION TK_menorIgual EXPRESION |
            EXPRESION TK_mayor EXPRESION |
            EXPRESION TK_menor EXPRESION ;

LOGICAS ::=
            EXPRESION TK_and EXPRESION |
            EXPRESION TK_or EXPRESION  |
            TK_not EXPRESION ;

FUNCIONES ::=
            PR_get_move TK_parA EXPRESION TK_coma EXPRESION TK_parC |
            PR_last_move TK_parA EXPRESION TK_parC                  |
            PR_get_moves_count TK_parA EXPRESION TK_coma EXPRESION TK_parC |
            PR_get_last_n_moves TK_parA EXPRESION TK_coma EXPRESION TK_parC;

LISTA ::= TK_corcheteA ELEMENTOS TK_corcheteC ;

ELEMENTOS ::=
            ELEMENTOS TK_coma EXPRESION |
            EXPRESION ;

DECISION ::=
            PR_C :d {: RESULT = new Primitivo(d, Tipo.DECISION); :} |
            PR_D :d {: RESULT = new Primitivo(d, Tipo.DECISION); :} ;