
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizers;

/** CUP generated class containing symbol constants. */
public class Terminal {
  /* terminals */
  public static final int error = 1;
  public static final int TK_numero = 3;
  public static final int TK_suma = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_suma",
  "TK_numero"
  };
}

