
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Lenguaje;

/** CUP generated class containing symbol constants. */
public class Terminal {
  /* terminals */
  public static final int RW_traicionado = 23;
  public static final int TK_coma = 48;
  public static final int TK_menorIgual = 36;
  public static final int RW_traidor = 22;
  public static final int RW_scoring = 19;
  public static final int RW_main = 24;
  public static final int TK_menor = 35;
  public static final int TK_mayorIgual = 37;
  public static final int RW_true = 49;
  public static final int RW_opponent_history = 52;
  public static final int RW_round_number = 14;
  public static final int TK_mayor = 34;
  public static final int TK_or = 38;
  public static final int get_last_n_moves = 13;
  public static final int RW_false = 50;
  public static final int RW_random = 51;
  public static final int RW_strategies = 17;
  public static final int RW_else = 9;
  public static final int TK_id = 29;
  public static final int EOF = 0;
  public static final int RW_cooperacionM = 20;
  public static final int RW_initial = 3;
  public static final int error = 1;
  public static final int TK_llaveC = 42;
  public static final int TK_diferente = 33;
  public static final int TK_llaveA = 41;
  public static final int RW_then = 8;
  public static final int RW_players = 16;
  public static final int RW_seed = 27;
  public static final int TK_not = 40;
  public static final int TK_and = 39;
  public static final int RW_defeccionnM = 21;
  public static final int TK_parC = 46;
  public static final int RW_get_last_n_moves = 28;
  public static final int TK_parA = 45;
  public static final int RW_rules = 6;
  public static final int RW_match = 15;
  public static final int RW_self_history = 53;
  public static final int RW_with = 26;
  public static final int RW_get_move = 10;
  public static final int TK_corcheteC = 44;
  public static final int RW_D = 5;
  public static final int TK_dosPuntos = 47;
  public static final int RW_C = 4;
  public static final int TK_corcheteA = 43;
  public static final int RW_get_moves_count = 12;
  public static final int RW_rounds = 18;
  public static final int TK_enteros = 30;
  public static final int RW_if = 7;
  public static final int RW_run = 25;
  public static final int RW_strategy = 2;
  public static final int TK_decimales = 31;
  public static final int RW_last_move = 11;
  public static final int TK_igual = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RW_strategy",
  "RW_initial",
  "RW_C",
  "RW_D",
  "RW_rules",
  "RW_if",
  "RW_then",
  "RW_else",
  "RW_get_move",
  "RW_last_move",
  "RW_get_moves_count",
  "get_last_n_moves",
  "RW_round_number",
  "RW_match",
  "RW_players",
  "RW_strategies",
  "RW_rounds",
  "RW_scoring",
  "RW_cooperacionM",
  "RW_defeccionnM",
  "RW_traidor",
  "RW_traicionado",
  "RW_main",
  "RW_run",
  "RW_with",
  "RW_seed",
  "RW_get_last_n_moves",
  "TK_id",
  "TK_enteros",
  "TK_decimales",
  "TK_igual",
  "TK_diferente",
  "TK_mayor",
  "TK_menor",
  "TK_menorIgual",
  "TK_mayorIgual",
  "TK_or",
  "TK_and",
  "TK_not",
  "TK_llaveA",
  "TK_llaveC",
  "TK_corcheteA",
  "TK_corcheteC",
  "TK_parA",
  "TK_parC",
  "TK_dosPuntos",
  "TK_coma",
  "RW_true",
  "RW_false",
  "RW_random",
  "RW_opponent_history",
  "RW_self_history"
  };
}

